# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('F', 'Primeiro Jogador Vence'), ('S', 'Segundo Jogador Vence'), ('D', 'Empate')], default='A', max_length=1),
        ),
    ]
